-- Requires permissions to create database, schemas and tables.
-- Run explicitly in a dev account; never use a production database for this lab.
CREATE DATABASE IF NOT EXISTS MUSIC_LAB;
CREATE SCHEMA IF NOT EXISTS MUSIC_LAB.RAW;
CREATE SCHEMA IF NOT EXISTS MUSIC_LAB.CURATED;
CREATE SCHEMA IF NOT EXISTS MUSIC_LAB.FEATURES;
CREATE SCHEMA IF NOT EXISTS MUSIC_LAB.ML;
CREATE FILE FORMAT IF NOT EXISTS MUSIC_LAB.RAW.CSV_FORMAT TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"';
CREATE STAGE IF NOT EXISTS MUSIC_LAB.RAW.CSV_STAGE FILE_FORMAT = MUSIC_LAB.RAW.CSV_FORMAT;
CREATE TABLE IF NOT EXISTS MUSIC_LAB.RAW.USERS (USER_ID INTEGER, PREFERRED_GENRE VARCHAR);
CREATE TABLE IF NOT EXISTS MUSIC_LAB.RAW.TRACKS (TRACK_ID INTEGER, TITLE VARCHAR, GENRE VARCHAR);
CREATE TABLE IF NOT EXISTS MUSIC_LAB.RAW.LISTENING_EVENTS (EVENT_ID INTEGER, USER_ID INTEGER, TRACK_ID INTEGER, PLAYED_AT TIMESTAMP_NTZ, COMPLETION_RATE FLOAT, SKIPPED INTEGER);
