-- Upload CSVs to @MUSIC_LAB.RAW.CSV_STAGE using Snowsight or SnowSQL/CLI first.
-- Expected stage paths: @MUSIC_LAB.RAW.CSV_STAGE/users.csv etc.
COPY INTO MUSIC_LAB.RAW.USERS FROM @MUSIC_LAB.RAW.CSV_STAGE/users.csv FILE_FORMAT = (FORMAT_NAME = 'MUSIC_LAB.RAW.CSV_FORMAT') ON_ERROR = 'ABORT_STATEMENT';
COPY INTO MUSIC_LAB.RAW.TRACKS FROM @MUSIC_LAB.RAW.CSV_STAGE/tracks.csv FILE_FORMAT = (FORMAT_NAME = 'MUSIC_LAB.RAW.CSV_FORMAT') ON_ERROR = 'ABORT_STATEMENT';
COPY INTO MUSIC_LAB.RAW.LISTENING_EVENTS FROM @MUSIC_LAB.RAW.CSV_STAGE/listening_events.csv FILE_FORMAT = (FORMAT_NAME = 'MUSIC_LAB.RAW.CSV_FORMAT') ON_ERROR = 'ABORT_STATEMENT';
