-- Simple SQL feature baseline. Feature Store objects and refreshes are a later milestone.
CREATE OR REPLACE VIEW MUSIC_LAB.FEATURES.USER_GENRE_AFFINITY AS
SELECT e.USER_ID, t.GENRE, COUNT(*) AS PLAY_COUNT,
       AVG(e.COMPLETION_RATE) AS AVG_COMPLETION_RATE,
       AVG(IFF(e.SKIPPED = 1, 1.0, 0.0)) AS SKIP_RATE
FROM MUSIC_LAB.RAW.LISTENING_EVENTS e
JOIN MUSIC_LAB.RAW.TRACKS t ON e.TRACK_ID = t.TRACK_ID
GROUP BY e.USER_ID, t.GENRE;

CREATE OR REPLACE VIEW MUSIC_LAB.FEATURES.TRACK_ENGAGEMENT AS
SELECT TRACK_ID, COUNT(*) AS TOTAL_PLAYS,
       AVG(COMPLETION_RATE) AS AVG_COMPLETION_RATE,
       COUNT(DISTINCT USER_ID) AS UNIQUE_LISTENERS
FROM MUSIC_LAB.RAW.LISTENING_EVENTS GROUP BY TRACK_ID;
