-- Each query should return zero violations.
SELECT 'invalid_completion_rate' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM MUSIC_LAB.RAW.LISTENING_EVENTS WHERE COMPLETION_RATE NOT BETWEEN 0 AND 1
UNION ALL
SELECT 'orphan_track', COUNT(*) FROM MUSIC_LAB.RAW.LISTENING_EVENTS e
LEFT JOIN MUSIC_LAB.RAW.TRACKS t ON e.TRACK_ID = t.TRACK_ID WHERE t.TRACK_ID IS NULL
UNION ALL
SELECT 'orphan_user', COUNT(*) FROM MUSIC_LAB.RAW.LISTENING_EVENTS e
LEFT JOIN MUSIC_LAB.RAW.USERS u ON e.USER_ID = u.USER_ID WHERE u.USER_ID IS NULL
UNION ALL
SELECT 'duplicate_event', COUNT(*) FROM (
  SELECT EVENT_ID FROM MUSIC_LAB.RAW.LISTENING_EVENTS GROUP BY EVENT_ID HAVING COUNT(*) > 1
);
