-- LIVE: SQL incremental transformations. Inspect REFRESH_MODE after creation.
-- No wall-clock CURRENT_TIMESTAMP expression in the dynamic table transformation.
CREATE OR REPLACE DYNAMIC TABLE MUSIC_LAB.FEATURES.EVENTS_CANONICAL
 TARGET_LAG = '1 minute'
 WAREHOUSE = MUSIC_LAB_XS
 REFRESH_MODE = AUTO
 AS
 SELECT TENANT_ID, EVENT_ID, USER_ID, CONTENT_ID, EVENT_TS, EVENT_TYPE, COMPLETION_RATE
 FROM MUSIC_LAB.STREAM.EVENTS
 QUALIFY ROW_NUMBER() OVER (PARTITION BY TENANT_ID, EVENT_ID ORDER BY EVENT_TS DESC) = 1;

CREATE OR REPLACE DYNAMIC TABLE MUSIC_LAB.FEATURES.DT_USER_COUNTS
 TARGET_LAG = '1 minute'
 WAREHOUSE = MUSIC_LAB_XS
 REFRESH_MODE = AUTO
 AS
 SELECT TENANT_ID, USER_ID,
        COUNT(*) AS EVENTS,
        COUNT_IF(EVENT_TYPE = 'listen') AS LISTENS,
        AVG(COMPLETION_RATE) AS AVG_COMPLETION,
        MAX(EVENT_TS) AS LATEST_EVENT_TS
 FROM MUSIC_LAB.FEATURES.EVENTS_CANONICAL
 GROUP BY TENANT_ID, USER_ID;

-- Verify actual effective refresh mode and compute cost in Snowsight.
SHOW DYNAMIC TABLES IN SCHEMA MUSIC_LAB.FEATURES;
-- As-of feature correctness and late/replayed event behavior must be tested separately.
