-- Post-ingest invariants. These queries must be zero (except lag, which is sampled).
SELECT COUNT(*) AS DUPLICATE_KEYS
FROM (SELECT TENANT_ID, EVENT_ID, COUNT(*) N
      FROM MUSIC_LAB.FEATURES.EVENTS_CANONICAL
      GROUP BY TENANT_ID, EVENT_ID HAVING COUNT(*) > 1);
SELECT COUNT(*) AS INVALID_COMPLETIONS
FROM MUSIC_LAB.FEATURES.EVENTS_CANONICAL
WHERE COMPLETION_RATE < 0 OR COMPLETION_RATE > 1;
SELECT COUNT(*) AS MISSING_TENANTS
FROM MUSIC_LAB.FEATURES.EVENTS_CANONICAL
WHERE TENANT_ID IS NULL;
SELECT DATEDIFF('second', MAX(EVENT_TS), CURRENT_TIMESTAMP()) AS LAST_EVENT_AGE_SECONDS
FROM MUSIC_LAB.FEATURES.EVENTS_CANONICAL;
-- Last event age is not event-to-online-feature freshness. Measure E2E separately.
